#!/system/bin/sh
# TIPS: Use CTRL + S to save
# TIPS: Use CTRL + X to exit
binname=$(cat .tmps)
p2() {
cp $arg.dec.sh /sdcard/ShellEncrypter/output > /dev/null
rm $arg.dec.sh > /dev/null
echo "[√] Succes, Check the output in /sdcard/ShellEncrypter/output"
echo 
echo "Decrypt again? (y/n)"
echo -n ": "
read asw
if [[ $asw == "y" ]]; then
dec ./$binname
elif [[ $asw == "n" ]]; then
rm $binname
rm .tmps
enc
fi
}

for arg in $@
do
  echo "[~] Decrypting Binary..."
  echo "[*] Note: Not all Android Devices support this feature."
  $arg > /dev/null & child=$!
  sleep 0.04
  kill -STOP $child
  cat /proc/$child/cmdline > "$arg.dec.sh"
  kill -TERM $child
  p2
done