#!/data/data/com.termux/files/usr/bin/bash
# Source library
. /sdcard/ShellUtility/.lib/libenc.sh

# Get binary name from .tmps file
binname=$(cat .tmps)

# Function to handle post-decryption tasks
p2() {
    sudo cp $arg.dec.sh ${SP}/output
    sudo rm $arg.dec.sh
    echo "[√] Success, Check the output in ${SP}/output"
    echo 
    echo "Decrypt again? (y/n)"
    echo -n ": "
    read asw
    if [[ $asw == "y" ]]; then
        dec ./$binname
    elif [[ $asw == "n" ]]; then
        sudo rm $binname
        sudo rm .tmps
        enc
    fi
}

# Loop through each argument
for arg in $@
do
    echo "[~] Decrypting Binary..."
    echo "[*] Note: Not all Android Devices support this feature."
    
    # Run binary in background
    $arg > /dev/null & child=$!
    sleep 0.08
    kill -STOP $child
    
    # Get binary command line and save to a file
    cat /proc/$child/cmdline > "$arg.dec.sh"
    kill -TERM $child
    
    # Perform post-decryption tasks
    p2
done
