#!/usr/bin/bash
binname=$(cat .tmps)
# main
p2() {
rm $binname
rm .tmps
cp $arg.dec.sh /sdcard/ShellEncrypter/output
rm $arg.dec.sh
echo "[√] Succes, Check the output in /sdcard/ShellEncrypter/output"
}

for arg in $@
do
  echo "[~] Decrypting Binary..."
  echo "[*] Don't Panic if an error occurs"
  $arg >> "/sdcard/log" & child=$!
  sleep 0.05
  kill -STOP $child
  cat /proc/$child/cmdline > "$arg.dec.sh"
  kill -TERM $child
  p2
  exit 
done
